name: Download and Upload File

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'Direct file URL to download'
        required: true
        default: 'https://prod.downloadnow.com/9d6/f04/5a0d1ed20fd187e51f639070e81c85b717/Warcraft-III-Setup-1-31-Windows.zip?Expires=1740600757&Signature=a2cabd27ca3f733fd7c9ace9659bc81af4802c94&url=[...]

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Git LFS
        run: git lfs install

      - name: Download file
        run: |
          # Create downloads directory if it doesn't exist
          mkdir -p downloads
          # Download the file using curl
          curl -L "${{ github.event.inputs.file_url }}" -o "downloads/downloaded_file"
        
      - name: Track large file with Git LFS
        run: git lfs track "downloads/downloaded_file"

      - name: Verify file contents
        run: ls -la downloads/

      - name: Commit and push file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .gitattributes downloads/downloaded_file
          git commit -m "Add downloaded file to Git LFS" || echo "Nothing to commit"
          git push
