name: Download and Upload File

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'Direct file URL to download'
        required: true
        default: 'https://prod.downloadnow.com/9d6/f04/5a0d1ed20fd187e51f639070e81c85b717/Warcraft-III-Setup-1-31-Windows.zip?Expires=1741526038&Signature=e7a4ed84a90079f4bd1f16ac6948187930b16be1&url=https://download.cnet.com/warcraft-iii-the-frozen-throne/3000-windows-warcraft-3-the-frozen-throne.html&Filename=Warcraft-III-Setup-1-31-Windows.zip'
jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Git LFS
        run: git lfs install

      - name: Download file
        run: |
          # Create downloads directory if it doesn't exist
          mkdir -p downloads
          # Download the file using curl
          curl -L "${{ github.event.inputs.file_url }}" -o "downloads/downloaded_file"
        
      - name: Track large file with Git LFS
        run: git lfs track "downloads/downloaded_file"

      - name: Commit and push file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .gitattributes downloads/downloaded_file
          git commit -m "Add downloaded file to Git LFS"
          git push
